/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_app;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

class App {
	public String getGreeting() {
		return "Hello world.";
	}

	private static final EntityManagerFactory emFactoryObj;
	private static final String PERSISTENCE_UNIT_NAME = "JPAService";

	static {
		emFactoryObj = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME);
	}

	// This Method Is Used To Retrieve The 'EntityManager' Object
	private static EntityManager getEntityManager() {
		return emFactoryObj.createEntityManager();
	}

	public static void main(String[] args) {

		// JSON parser object to parse read file
		JSONParser jsonParser = new JSONParser();

		try {
			URL resource = App.class.getClassLoader().getResource("info.json");
			System.out.println(resource.toString());
			FileReader reader = new FileReader(resource.getFile());

			// Read JSON file
			Object obj = jsonParser.parse(reader);

			JSONArray infoList = (JSONArray) obj;
			System.out.println(infoList);

			Information i = new Information();

			List<Information> info = i.parseInformationObject(infoList);

			saveInformation(info);
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

		} catch (IOException e) {
			e.printStackTrace();
		} catch (ParseException e) {
			e.printStackTrace();
		}

	}

	private static void saveInformation(List<Information> inf) {
		EntityManager entityMgr = getEntityManager();
		entityMgr.getTransaction().begin();
		InformationEntity infObj = new InformationEntity();
		String id;
		long start_time;
		long end_time;
		long duration;
		for (int i = 0; i < inf.size(); i++) {
			if (inf.get(i).getState().equals("STARTED")) {
				id = inf.get(i).getId();
				start_time = inf.get(i).getTimestamp();

				final String _id = id;
				Information info1 = inf.stream().filter(customer -> _id.equals(customer.getId()))
						.filter(customer -> "FINISHED".equals(customer.getState())).findAny().orElse(null);

				end_time = info1.getTimestamp();
				duration = end_time - start_time;
				infObj.setDuration(duration);
				if (duration > 4) {
					infObj.setAlert(true);
				} else {
					infObj.setAlert(false);
				}

				if (inf.get(i).getHost() != null) {
					infObj.setHost(inf.get(i).getHost());
				} else {
					infObj.setHost(null);
				}
				if (inf.get(i).getType() != null) {
					infObj.setType_(inf.get(i).getType());
				} else {
					infObj.setType_(null);
				}
				infObj.setId_(id);

				entityMgr.merge(infObj);
			} else {
				continue;
			}

		}

		entityMgr.getTransaction().commit();

		entityMgr.clear();
		System.out.println("Records Successfully Inserted In The Database");
	}

}
